"""empty message

Revision ID: 043e0c06bf1d
Revises: bd497866a9ea
Create Date: 2022-12-21 21:38:01.661732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '043e0c06bf1d'
down_revision = 'bd497866a9ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('replies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('replies', schema=None) as batch_op:
        batch_op.drop_column('create_date')

    # ### end Alembic commands ###
