"""empty message

Revision ID: 1094fa7d3292
Revises: e4bd94891b61
Create Date: 2022-11-23 13:16:25.689151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1094fa7d3292'
down_revision = 'e4bd94891b61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogprofile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usersno', sa.Integer(), nullable=True))
        batch_op.drop_constraint('blogprofile_userid_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['usersno'], ['sno'])
        batch_op.drop_column('userid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogprofile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userid', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('blogprofile_userid_fkey', 'users', ['userid'], ['sno'])
        batch_op.drop_column('usersno')

    # ### end Alembic commands ###
