"""empty message

Revision ID: 10a288b77fb4
Revises: e56344fc96c1
Create Date: 2022-11-22 15:01:45.546500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10a288b77fb4'
down_revision = 'e56344fc96c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sub_comment')
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sno', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('to', sa.String(length=500), nullable=True))

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.String(length=200), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reading_lists', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('reading_lists')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('summary')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('to')
        batch_op.drop_column('sno')

    op.create_table('sub_comment',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('body', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['comment.id'], name='sub_comment_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='sub_comment_pkey')
    )
    # ### end Alembic commands ###
