"""empty message

Revision ID: 35ee147d4b57
Revises: 387b80df8922
Create Date: 2022-11-25 22:53:10.210727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35ee147d4b57'
down_revision = '387b80df8922'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('reading_lists')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reading_lists', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
