"""empty message

Revision ID: 387b80df8922
Revises: 572f2c871dcc
Create Date: 2022-11-25 22:49:59.244552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '387b80df8922'
down_revision = '572f2c871dcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reading_lists')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reading_lists',
    sa.Column('sno', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usersno', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['usersno'], ['users.sno'], name='reading_lists_usersno_fkey'),
    sa.PrimaryKeyConstraint('sno', name='reading_lists_pkey')
    )
    # ### end Alembic commands ###
