"""empty message

Revision ID: 3ea2f4209fef
Revises: 7e2ee7752454
Create Date: 2022-11-24 15:52:45.369888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ea2f4209fef'
down_revision = '7e2ee7752454'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogprofile', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['usersno'], ['sno'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogprofile', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
