"""empty message

Revision ID: 572f2c871dcc
Revises: 3ea2f4209fef
Create Date: 2022-11-25 22:40:41.479968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '572f2c871dcc'
down_revision = '3ea2f4209fef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading_lists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usersno', sa.Integer(), nullable=True))
        batch_op.drop_constraint('reading_lists_userid_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['usersno'], ['sno'])
        batch_op.drop_column('userid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading_lists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userid', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('reading_lists_userid_fkey', 'users', ['userid'], ['sno'])
        batch_op.drop_column('usersno')

    # ### end Alembic commands ###
