"""empty message

Revision ID: 63d6bfd874e9
Revises: 
Create Date: 2022-12-20 12:30:47.112534

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '63d6bfd874e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('sno', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usersno', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('body', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('to', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('create_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['usersno'], ['users.sno'], name='comment_usersno_fkey'),
    sa.PrimaryKeyConstraint('sno', name='comment_pkey')
    )
    # ### end Alembic commands ###
