"""empty message

Revision ID: 640b6c7b6a74
Revises: 18fb61703670
Create Date: 2022-11-18 20:17:43.737491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '640b6c7b6a74'
down_revision = '18fb61703670'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('picture')

    # ### end Alembic commands ###
