"""empty message

Revision ID: 7989f3f5a3b9
Revises: 043e0c06bf1d
Create Date: 2022-12-21 22:11:46.510413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7989f3f5a3b9'
down_revision = '043e0c06bf1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('replies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usersno', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['usersno'], ['sno'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('replies', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('usersno')

    # ### end Alembic commands ###
