"""empty message

Revision ID: 7bfd659c3d8b
Revises: 10a288b77fb4
Create Date: 2022-11-22 15:31:47.078254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bfd659c3d8b'
down_revision = '10a288b77fb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('body', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('sno', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('to', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.sno'], name='comment_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='comment_pkey')
    )
    # ### end Alembic commands ###
