"""empty message

Revision ID: 7e2ee7752454
Revises: 1094fa7d3292
Create Date: 2022-11-23 13:28:03.335641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e2ee7752454'
down_revision = '1094fa7d3292'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogprofile', schema=None) as batch_op:
        batch_op.alter_column('usersno',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('blogprofile_usersno_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogprofile', schema=None) as batch_op:
        batch_op.create_foreign_key('blogprofile_usersno_fkey', 'users', ['usersno'], ['sno'])
        batch_op.alter_column('usersno',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
