"""empty message

Revision ID: 89cabad7be82
Revises: d854552d44e1
Create Date: 2022-11-30 11:48:01.320833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89cabad7be82'
down_revision = 'd854552d44e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint('posts_shorturl_fkey', type_='foreignkey')
        batch_op.drop_column('shorturl')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shorturl', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('posts_shorturl_fkey', 'urlshortner', ['shorturl'], ['sno'])

    # ### end Alembic commands ###
