"""empty message

Revision ID: bd497866a9ea
Revises: e46315020618
Create Date: 2022-12-21 21:13:33.437484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd497866a9ea'
down_revision = 'e46315020618'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint('comments_parent_fkey', type_='foreignkey')
        batch_op.drop_column('parent')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('comments_parent_fkey', 'comments', ['parent'], ['sno'])

    # ### end Alembic commands ###
