"""empty message

Revision ID: d7753e7c1833
Revises: 3565d6c6e4f6
Create Date: 2022-11-29 23:44:37.275154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7753e7c1833'
down_revision = '3565d6c6e4f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shorturl', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'urlshortner', ['shorturl'], ['sno'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('shorturl')

    # ### end Alembic commands ###
