"""empty message

Revision ID: d854552d44e1
Revises: d7753e7c1833
Create Date: 2022-11-30 11:08:30.095723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd854552d44e1'
down_revision = 'd7753e7c1833'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('urlshortner', schema=None) as batch_op:
        batch_op.alter_column('pointer',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=8),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('urlshortner', schema=None) as batch_op:
        batch_op.alter_column('pointer',
               existing_type=sa.String(length=8),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)

    # ### end Alembic commands ###
