"""empty message

Revision ID: e46315020618
Revises: 7a48cf4897d3
Create Date: 2022-12-21 10:56:09.802654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e46315020618'
down_revision = '7a48cf4897d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'comments', ['parent'], ['sno'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('parent')

    # ### end Alembic commands ###
